### ISSUE TITLE
Fix authentication

### ISSUE THREAD

**Issue by ryanfb** [ryanfb/google-fusion-tables-backup#2]
Currently get:

```
/Users/ryan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gdata_19-1.1.5/lib/gdata/auth/clientlogin.rb:85:in `get_token': request error 404: https://developers.google.com/accounts/docs/AuthForInstalledApps (GData::Client::AuthorizationError)
        from /Users/ryan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gdata_19-1.1.5/lib/gdata/client/base.rb:157:in `clientlogin'
        from ./google-fusion-tables-backup.rb:41:in `<main>'
```

This is because the `fusion_tables` gem depends on the `gdata_19` gem for authentication, which uses the deprecated [ClientLogin for Installed Applications](https://developers.google.com/identity/protocols/AuthForInstalledApps) API.

Looks like the only viable alternative is to completely switch to [the `google-api-client` gem](https://developers.google.com/api-client-library/ruby/apis/fusiontables/v2).

**Comment by vivek2007** [comment]
HI @ryanfb 

Hi all, i am facing with OAuth version can you please help me

request error 404: https://developers.google.com/accounts/docs/AuthForInstalledApps
/home/vivek/.rvm/gems/ruby-1.9.2-p290/gems/gdata_19-1.1.5/lib/gdata/auth/clientlogin.rb:85:in get_token' /home/vivek/.rvm/gems/ruby-1.9.2-p290/gems/gdata_19-1.1.5/lib/gdata/client/base.rb:157:inclientlogin'
/home/vivek/Documents/GTFS1/inc/ft.rb:10:in init' /home/vivek/Documents/GTFS1/inc/ft.rb:99:ingetTable'
/home/vivek/Documents/GTFS1/inc/ft.rb:28:in update' /home/vivek/Documents/GTFS1/Rakefile:435:inblock (3 levels) in '
/home/vivek/Documents/GTFS1/Rakefile:434:in each' /home/vivek/Documents/GTFS1/Rakefile:434:inblock (2 levels) in '
/home/vivek/.rvm/gems/ruby-1.9.2-p290/bin/ruby_executable_hooks:15:in eval' /home/vivek/.rvm/gems/ruby-1.9.2-p290/bin/ruby_executable_hooks:15:in

'
Tasks: TOP => project:deploy_fusiontables
(See full trace by running task with --trace)
vivek@vivek:~/Documents/GTFS1$ rake project:deploy_fusiontables
07:41:35 +0 : START Fusion Tables INSERTs
rake aborted!
request error 404: https://developers.google.com/accounts/docs/AuthForInstalledApps
/home/vivek/.rvm/gems/ruby-1.9.2-p290/gems/gdata_19-1.1.5/lib/gdata/auth/clientlogin.rb:85:in get_token' /home/vivek/.rvm/gems/ruby-1.9.2-p290/gems/gdata_19-1.1.5/lib/gdata/client/base.rb:157:inclientlogin'
/home/vivek/Documents/GTFS1/inc/ft.rb:10:in init' /home/vivek/Documents/GTFS1/inc/ft.rb:99:ingetTable'
/home/vivek/Documents/GTFS1/inc/ft.rb:28:in update' /home/vivek/Documents/GTFS1/Rakefile:435:inblock (3 levels) in '
/home/vivek/Documents/GTFS1/Rakefile:434:in each' /home/vivek/Documents/GTFS1/Rakefile:434:inblock (2 levels) in '
/home/vivek/.rvm/gems/ruby-1.9.2-p290/bin/ruby_executable_hooks:15:in eval' /home/vivek/.rvm/gems/ruby-1.9.2-p290/bin/ruby_executable_hooks:15:in'
Tasks: TOP => project:deploy_fusiontables
(See full trace by running task with --trace)

**Comment by ryanfb** [comment]
It looks like vasile/GTFS-viz#11 would also need to be fixed by migrating away from the `fusion_tables` gem like I did with https://github.com/ryanfb/google-fusion-tables-backup/pull/3

Either that or someone would need to update/fix/fork [tokumine/fusion_tables](https://github.com/tokumine/fusion_tables) to use the V2 API + authentication.
